"""
Set KUAIYU USB MIC (card 2) as the default ALSA sound card on Debian/RK3568.
Persists across reboots via /etc/asound.conf.
"""
import paramiko

HOST = "192.168.0.100"
USER = "rock"
PASS = "rock"

# USB MIC is card 2
USB_CARD = 2

ASOUND_CONF = f"""\
# /etc/asound.conf - Set USB audio (card {USB_CARD}) as default
# Generated by set_default_audio.py

defaults.pcm.card {USB_CARD}
defaults.ctl.card {USB_CARD}
"""

ssh = paramiko.SSHClient()
ssh.set_missing_host_key_policy(paramiko.AutoAddPolicy())
ssh.connect(HOST, username=USER, password=PASS, timeout=10)

def run(cmd, timeout=15):
    _, o, e = ssh.exec_command(cmd, timeout=timeout)
    out = o.read().decode().strip()
    err = e.read().decode().strip()
    if out: print(out)
    if err and 'sudo' not in err and 'password' not in err.lower(): print('[ERR]', err[:200])
    return out

def sudo_run(cmd, timeout=15):
    return run(f"echo {PASS} | sudo -S sh -c '{cmd}'", timeout)

print("=== Before change: default ALSA card ===")
run("aplay -l 2>/dev/null | grep -i 'usb' || echo '(USB device listing...)'", timeout=5)

# Write /etc/asound.conf
print(f"\n=== Writing /etc/asound.conf (card {USB_CARD} = USB MIC) ===")
sftp = ssh.open_sftp()
with sftp.open('/tmp/asound.conf', 'wb') as f:
    f.write(ASOUND_CONF.encode('utf-8'))
sftp.close()
sudo_run("cp /tmp/asound.conf /etc/asound.conf && chmod 644 /etc/asound.conf")

print("\n=== /etc/asound.conf content ===")
run("cat /etc/asound.conf")

# Verify with aplay/arecord
print("\n=== Verification ===")
run("aplay -l 2>/dev/null | head -20", 5)

# Also update ~/.asoundrc for user-level if needed
print("\n=== Setting ~/.asoundrc for user rock ===")
asoundrc = f"""\
defaults.pcm.card {USB_CARD}
defaults.ctl.card {USB_CARD}
"""
sftp = ssh.open_sftp()
with sftp.open('/home/rock/.asoundrc', 'wb') as f:
    f.write(asoundrc.encode('utf-8'))
sftp.close()
run("cat /home/rock/.asoundrc")

print("\n=== Quick record test (1s from USB MIC) ===")
result = run(f"arecord -D plughw:{USB_CARD},0 -r 16000 -f S16_LE -c 1 -d 1 /tmp/test.wav 2>&1 || true", 8)
if 'error' not in result.lower():
    print("Capture OK!")
    run("rm -f /tmp/test.wav", 5)

ssh.close()
print("\nDone! USB MIC (card 2) is now the default ALSA device.")
print("This setting persists across reboots via /etc/asound.conf and ~/.asoundrc")
